<?php 

	function capgrid_tweaks_user_presave(Drupal\Core\Entity\EntityInterface $entity) {
		if($entity->isNew()) {
			if($entity->get("field_profile_type")->value === "supplier"){
				$entity->addRole('supplier');
			}
			else{
				$entity->addRole('purchaser');
			}
		}
	}

	function capgrid_tweaks_mail($key, &$message, $params) {
		$options = array(
			'langcode' => $message['langcode'],
		);
	 
		switch ($key) {
			case 'send_nda_document':
				$message['from'] = \Drupal::config('system.site')->get('mail');
				$message['subject'] = $params['subject'];
				$message['body'][] = $params['message'];
				$message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
				break;
		}
	 }
